@baseUrl = http://localhost:3000
@bearerAuth = Bearer {{signin.response.body.accessToken}}

### create user
# @name createuser
POST {{baseUrl}}/users
Content-Type: application/json
Accept: : application/json

{
  "email": "batman@email.com",
  "password": "12345678"
}

### Upload Single Picture
# @name uploadPicture
POST {{baseUrl}}/users/upload-picture
Authorization: {{bearerAuth}}
Content-Type: multipart/form-data; boundary=----BoundaryDelimitadorHttp

------BoundaryDelimitadorHttp
Content-Disposition: form-data; name="file"; filename="img.jpg"
Content-Type: image/jpeg

< ./dev/images/img.jpg 
------BoundaryDelimitadorHttp--


### Upload Multiple Pictures
# @name uploadPictures
POST {{baseUrl}}/users/upload-pictures
Authorization: {{bearerAuth}}
Content-Type: multipart/form-data; boundary=----BoundaryDelimitadorHttp

------BoundaryDelimitadorHttp
Content-Disposition: form-data; name="file"; filename="img.jpg"
Content-Type: image/jpeg

< ./dev/images/img.jpg 
------BoundaryDelimitadorHttp
Content-Disposition: form-data; name="file"; filename="img.jpg"
Content-Type: image/jpeg

< ./dev/images/img2.jpg 
------BoundaryDelimitadorHttp--



### signin
# @name signin
POST {{baseUrl}}/auth/signin
Content-Type: application/json
Accept: : application/json

{
  "email": "batman@email.com",
  "password": "12345678"
}
