@baseUrl = http://localhost:3000
@bearerAuth = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJiYXRtYW5AZW1haWwuY29tIiwiaWF0IjoxNzMwMTI0MzEwLCJleHAiOjE3MzAxMjc5MTAsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMCIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMCJ9.YvhXNZ18vE2ubk92WTMFV6xwOg09hx0Hjb3sE3A87uo

### create user
POST {{baseUrl}}/users
Content-Type: application/json
Accept: : application/json

{
  "email": "batman@email.com",
  "password": "12345678"
}


### find user by id
GET {{baseUrl}}/users/1
Accept: : application/json
Authorization: {{bearerAuth}}



### signin
POST {{baseUrl}}/auth/signin
Content-Type: application/json
Accept: : application/json

{
  "email": "batman@email.com",
  "password": "12345678"
}
