
@baseUrl = http://localhost:3000

###
POST {{baseUrl}}/recados
Content-Type: application/json

{
  "to": "9",
  "from": "de 5",
  "text": "Ola mundo 5!!"
}

###
GET {{baseUrl}}/recados
?page=1
&size=10
&q=mundo
###

###
GET {{baseUrl}}/recados/1
###

###
PATCH {{baseUrl}}/recados/1
Content-Type: application/json

{
  "to": "de 9",
  "from": "de 5",
  "text": "Ola mundo 55555!!"
}

###
DELETE {{baseUrl}}/recados/1
