
@baseUrl = http://localhost:3000

## Pessoas
POST {{baseUrl}}/pessoas
Content-Type: application/json

{
  "email": "batman2@email.com",
  "password": "!@12bbAA",
  "name": "Batman da Silva"
}

###
GET {{baseUrl}}/pessoas/2

### 
PATCH {{baseUrl}}/pessoas/11
Content-Type: application/json

{
  "email": "batman10@email.com",
  "password": "99!@12bbAA",
  "name": "Batman da Silva 99"
}

###
DELETE {{baseUrl}}/pessoas/11

## Recados
###
POST {{baseUrl}}/recados
Content-Type: application/json

{
  "fromPessoaId": 1,
  "toPessoaId": 2,
  "text": "Ola mundo 5!!"
}

###
GET {{baseUrl}}/recados
?page=1
&size=10
&q=mundo
###

###
GET {{baseUrl}}/recados/1
###

###
PATCH {{baseUrl}}/recados/1
Content-Type: application/json

{
  "to": "de 11",
  "from": "de 5",
  "text": "Ola mundo2 123!!",
  "read": true
}

###
DELETE {{baseUrl}}/recados/1
