
@baseUrl = http://localhost:3000

###
POST {{baseUrl}}/recados
Content-Type: application/json

{
  "message": "OPA!"  
}

###
GET {{baseUrl}}/recados
###

###
GET {{baseUrl}}/recados/e71b0787-d7ae-4f1a-b9c2-914d616936fd
###

###
PATCH {{baseUrl}}/recados/e71b0787-d7ae-4f1a-b9c2-914d616936fd
Content-Type: application/json

{
  "message": "OPA!232"  
}

###
DELETE {{baseUrl}}/recados/e71b0787-d7ae-4f1a-b9c2-914d616936fd
